export const sampleProducts = [
  {
    name: 'MacBook Pro 16-inch',
    description: 'Apple M2 Pro chip, 16GB RAM, 512GB SSD',
    price: 2499990,
    image: '/images/macbook-pro.jpg',
    brand: 'Apple',
    category: 'Laptop văn phòng',
    parentCategory: 'Laptop',  // Thêm danh mục cha
    countInStock: 10,
    rating: 4.8,
    numReviews: 12,
  },
  {
    name: 'Dell XPS 15',
    description: '12th Gen Intel i7, 16GB RAM, 1TB SSD, RTX 3050 Ti',
    price: 1999990,
    image: '/images/dell-xps.jpg',
    brand: 'Dell',
    category: 'Laptop văn phòng',
    parentCategory: 'Laptop',
    countInStock: 8,
    rating: 4.7,
    numReviews: 10,
  },
  {
    name: 'Lenovo ThinkPad X1 Carbon',
    description: '11th Gen Intel i5, 16GB RAM, 256GB SSD',
    price: 1599990,
    image: '/images/thinkpad-x1.jpg',
    brand: 'Lenovo',
    category: 'Laptop văn phòng',
    parentCategory: 'Laptop',
    countInStock: 15,
    rating: 4.6,
    numReviews: 8,
  },
  {
    name: 'HP Envy x360',
    description: 'AMD Ryzen 7, 16GB RAM, 512GB SSD',
    price: 1299990,
    image: '/images/hp-envy.jpg',
    brand: 'HP',
    category: 'Laptop văn phòng',
    parentCategory: 'Laptop',
    countInStock: 12,
    rating: 4.5,
    numReviews: 15,
  },
  {
    name: 'ASUS ROG Zephyrus G14',
    description: 'AMD Ryzen 9, 32GB RAM, 1TB SSD, RTX 4060',
    price: 1899990,
    image: '/images/asus-rog.jpg',
    brand: 'ASUS',
    category: 'Laptop Gaming',
    parentCategory: 'Laptop',
    countInStock: 6,
    rating: 4.9,
    numReviews: 20,
  },
  // THÊM VÀI SẢN PHẨM KHÁC
  {
    name: 'Magic Keyboard',
    description: 'Bàn phím không dây Apple',
    price: 299000,
    image: '/images/magic-keyboard.jpg',
    brand: 'Apple',
    category: 'Bàn phím Apple',
    parentCategory: 'Phụ kiện',
    countInStock: 20,
    rating: 4.7,
    numReviews: 18,
  },
  {
    name: 'Keychron K2',
    description: 'Bàn phím cơ không dây, RGB',
    price: 199000,
    image: '/images/keychron-k2.jpg',
    brand: 'Keychron',
    category: 'Bàn phím cơ',
    parentCategory: 'Phụ kiện',
    countInStock: 25,
    rating: 4.8,
    numReviews: 30,
  }
];